name: Build Gym System
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Listar archivos (para depurar)
        run: dir /s  # Esto nos dirá en el log exactamente dónde está el .sln
      - name: Build
        run: dotnet build **/*.sln --configuration Release